## <center> Lecture 7 </center>
## <center> NumPy Arrays </center>

## Arrays
* An array is just a collection of numbers
* An array may have multiple dimensions
* Arrays allow mathematical operations on organized sets of numbers

# Array processing with NumPy
* In Python, array processing is implemented in the _NumPy_ library
* This library is heavily used by other libraries
* NumPy makes it easy to create, manipulate, and operate on arrays of any dimension

# Importing numpy

In [1]:
import numpy as np

* ```as np``` makes it easy to call numpy's methods

## Creating a 1-D array

In [2]:
my_array = np.array([0,1,1,2,3,5,8])

* In the above snippet, we have created an ```array``` from a ```list```
* To see this, let's obtain the ```type``` of our ```my_array``` object

In [3]:
type(my_array)

numpy.ndarray

## Creating a 2-D array
* A two-dimensional array can be created from a two-dimensional list
* Commas separate the _rows_ of the array:

In [4]:
my_2d_array = np.array([ [0,1,1,2],[3,5,8,11] ])

* Let's get the _shape_ of our array via the _shape_ attribute:

In [5]:
my_2d_array.shape

(2, 4)

* Our array has 2 rows and 4 columns

## Obtaining the type of the array elements
* NumPy arrays can hold different numeric types
* To see the type of your array, we can use the ```dtype``` attribute:

In [6]:
my_2d_array.dtype

dtype('int64')

* ```my_2d_array``` has integer elements, each represented by 64 bits

## Array types are set automatically
* Let's create a 1-D array of irrational numbers
* For this, we will need the ```math``` module, which we import:

In [7]:
import math
irr_arr = np.array([math.sqrt(2), math.sqrt(3), math.sqrt(5)])

* Let's inspect the contents of our array:

In [8]:
irr_arr

array([1.41421356, 1.73205081, 2.23606798])

* Now let's check out the ```type``` of the array's elements:

In [9]:
irr_arr.dtype

dtype('float64')

* NumPy is storing each element as a floating-point number with 64 bits

## Obtaining the number of dimensions
* The ```ndim``` attribute tells us how many dimensions are in our array:

In [10]:
irr_arr.ndim

1

In [11]:
my_2d_array.ndim

2

## Obtaining the total number of elements
* The ```size``` attribute tells us how many _elements_ are in our array

In [12]:
my_2d_array = np.array([ [0,1,1,2],[3,5,8,11] ])
my_2d_array.size

8

## Iterating through multi-dimensional arrays
* It is common to operate on each element of an array
* This can be achieved with numpy's iteration features

In [13]:
for row in my_2d_array:
    for col in row:
        print(col)

0
1
1
2
3
5
8
11


* ```for row in my_2d_array``` grabs each _row_ of the array
* ```for col in row``` then grabs each _element_ of ```row```

* Another way to iterate through ```my_2d_array``` is to use the ```.flat``` attribute:

In [14]:
for element in my_2d_array.flat:
    print(element)

0
1
1
2
3
5
8
11


## Creating an array of zeros

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Creating an array of ones

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Creating an array with a constant value

In [17]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

## Creating an array that spans a range
* NumPy's ```arange``` function allows you to create arrays that hold numbers filling a range

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* By default, ```np.arange``` begins at 0
* We can change this default behavior by calling the function with two arguments

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

* We can also modify the _interval_ to be something other than 1 by adding a 3rd argument

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## Creating floating-point ranges
* Sometimes we need to create a variable that holds a range of _continuous_ values
* This is accomplished with numpy's ```linspace``` function:

In [21]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

* Q: why did I set the 3rd argument to 6 instead of 5?

## Reshaping an array
* It is often required to transform an array into a different shape
* For example, we may want to view a 2-D array as a 'flat' column vector
* The ```reshape``` function will reshape your array to any allowable shape:

In [22]:
my_1d_array = np.arange(1,25)
my_1d_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

* Let's reshape the integers to a 4 by 6 array:

In [23]:
my_2d_array = my_1d_array.reshape((4,6))
my_2d_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

* And now let's reshape into a 1 by 24 array:

In [24]:
another_array = my_2d_array.reshape((1,24))

* Notice the shape of ```another_array```:

In [25]:
another_array.shape

(1, 24)

* ```another_array``` is technically still a 2-D array

* Contrast this with the shape of ```my_1d_array```:

In [26]:
my_1d_array.shape

(24,)

## Array operators
* NumPy allows you to perform mathematical operations on array
* _Element-wise_ operations: the operation is being performed individually one each element
* _Array_ operations: the operation is being applied to one or more arrays as a whole

## Element-wise multiplication and addition
* Adding 2 to each element of an array:

In [27]:
my_array = np.array([[1,2,3],[4,5,6]])

In [28]:
my_array + 2

array([[3, 4, 5],
       [6, 7, 8]])

* Multiplying each element of an array by 2:

In [29]:
my_array * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

* Squaring each array element:

In [30]:
my_array ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

## Multiplying two arrays element-by-element

In [31]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.full((2,3),2)

In [32]:
a1, a2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[2, 2, 2],
        [2, 2, 2]]))

In [33]:
a3 = a1 * a2
a3

array([[ 2,  4,  6],
       [ 8, 10, 12]])

* NB: notice that ```*``` performs element-wise and _not_ matrix multiplication!

## Adding two arrays element-by-element

In [34]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.full((2,3),2)

In [35]:
a1, a2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[2, 2, 2],
        [2, 2, 2]]))

In [36]:
a3 = a1 + a2
a3

array([[3, 4, 5],
       [6, 7, 8]])

## Comparing the elements of an array
* We can use Boolean expressions to test each element of an array
* Let's check whether each element of ```a3``` is an even number:

In [37]:
is_a3_even =  (a3%2) == 0 

In [38]:
a3, is_a3_even

(array([[3, 4, 5],
        [6, 7, 8]]),
 array([[False,  True, False],
        [ True, False,  True]]))

* The expression ```a3%2``` computes an array with the same size as ```a3```
* This array stores the remainder when dividing each element by 2:

In [39]:
a3%2

array([[1, 0, 1],
       [0, 1, 0]])

* The expression ```(a3%2)==0``` then compares the resulting remainders to 0:

In [40]:
(a3%2)==0

array([[False,  True, False],
       [ True, False,  True]])

## Comparing two arrays
* Boolean operations can also be performed on two arrays of the same size:

In [41]:
a1 = np.arange(10)
a2 = np.full((1,10),5)
a1, a2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]]))

* Let's check which elements in ```a1``` are greater than the _corresponding_ element in ```a2```

In [42]:
a1>a2

array([[False, False, False, False, False, False,  True,  True,  True,
         True]])

## Summing the elements of an array
* The ```sum()``` function allows you to easily sum the elements of your array:

In [43]:
my_array = np.arange(10)

In [44]:
my_array.sum()

45

* Let's see how ```sum()``` behaves when our array has more than 1 dimension

In [45]:
my_2d_array = my_array.reshape((2,5))
my_2d_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
my_2d_array.sum()

45

* The function computes the sum of _all_ array elements

## NumPy provides the related functions: 
* ```std()```: the standard deviation
* ```mean()```: the average of elements
* ```min()```: the lowest value
* ```max()```: the highest value


## What if you want to obtain the sum of each row or column?
* We can use the ```axis``` keyword argument to only sum up each row or column
* ```axis=0```: sum each _column_
* ```axis=1```: sum each _row_

In [ ]:
my_2d_array

In [ ]:
my_2d_array.sum(axis=0) ## Get the sum of each column

In [ ]:
my_2d_array.sum(axis=1) ## Get the sum of each row

## Array indexing and slicing
* It is often required to grab only a portion of an array
* This is accomplished with _slicing_
* NumPy's indexing scheme is similar to that that we saw for _lists_

* Let's create a 4 by 5 array of the integers 1 through 20

In [ ]:
my_array = np.arange(1,21).reshape((4,5))
my_array

* In the above, the function ```reshape()``` has been called on the _result_ of the function ```arange()```

* Let's grab the element at row 1, column 2 (indexed from 0!)

In [ ]:
my_array[1,2]

* Let's grab the entire first row (index 0):

In [ ]:
my_array[0,:]

* Get the first _and_ second rows:

In [ ]:
my_array[0:2,:]

* Q: why did I write ```0:2``` instead of ```0:1``` above?

* Get rows 0, 2, and 3

In [ ]:
my_array[[0,2,3],:]

* Get the first and second column:

In [ ]:
my_array[:,0:2]

* Get columns 0 and 3:

In [ ]:
my_array[:,[0,3]]

* Get the last column:

In [ ]:
my_array[:,-1]

## The _transpose_ of an array
* The tranpose of an array is another array where:
    * The rows of the new array are the columns of the old one
    * The columns of the new array are the rows of the old one

In [ ]:
my_array = np.array([[1,2,3],[4,5,6]])

In [ ]:
my_transpose = np.transpose(my_array)
my_transpose

* Let's verify the shapes of our arrays:

In [ ]:
print("The shape of my_array:", my_array.shape)
print("The shape of my_transpose:", my_transpose.shape)